import { ulid } from 'ulid'

/**
 * Storage key generation (Doc 12 §3, Doc 22 §9.4).
 *
 * Two rules, both security-relevant:
 *
 *  1. **A client filename never enters a key.** Uploaded names carry path
 *     traversal (`../../etc/passwd`), null bytes, and double extensions
 *     (`invoice.pdf.php`). The name is discarded at the boundary; only the
 *     server-detected MIME type decides the extension.
 *
 *  2. **The filename component is a ULID.** Time-sortable for operational
 *     convenience, 80 bits of entropy so a private key cannot be guessed even
 *     if the signed-URL layer were ever misconfigured.
 */

/** MIME type → canonical extension. `.jpeg` normalises to `.jpg` (Doc 12 §3). */
const EXTENSION_BY_MIME: Record<string, string> = {
  'image/jpeg': 'jpg',
  'image/png': 'png',
  'image/webp': 'webp',
  'application/pdf': 'pdf',
}

export function extensionForMime(mimeType: string): string | null {
  return EXTENSION_BY_MIME[mimeType.toLowerCase()] ?? null
}

/**
 * Reject anything that is not a plain forward-slash-separated relative key.
 *
 * Defence in depth for the local-disk backend, where a key becomes a
 * filesystem path. Keys are generated by this module and never accepted from a
 * request, so a violation means a programming error — it throws rather than
 * silently sanitising, which would hide the bug.
 */
const SAFE_KEY = /^[A-Za-z0-9][A-Za-z0-9._/-]{0,499}$/

export function assertSafeStorageKey(key: string): void {
  if (!SAFE_KEY.test(key) || key.includes('..') || key.includes('//')) {
    throw new Error('Unsafe storage key')
  }
}

/** `proofs/{bookingId}/{ulid}.{ext}` — PRIVATE bucket (Doc 12 §3). */
export function paymentProofKey(bookingId: string, extension: string): string {
  return `proofs/${bookingId}/${ulid()}.${extension}`
}

/** `courts/{courtId}/{ulid}.{ext}` — PUBLIC bucket (Doc 12 §3, Doc 24 §D.5). */
export function courtImageKey(courtId: string, extension: string): string {
  return `courts/${courtId}/${ulid()}.${extension}`
}

/** `cms/gallery/{ulid}.{ext}` — PUBLIC bucket (Doc 12 §3). */
export function cmsGalleryKey(extension: string): string {
  return `cms/gallery/${ulid()}.${extension}`
}

/** `cms/events/{ulid}.{ext}` — PUBLIC bucket (Doc 12 §3). */
export function cmsEventKey(extension: string): string {
  return `cms/events/${ulid()}.${extension}`
}

/** `cms/hero/{ulid}.{ext}` — PUBLIC bucket (Doc 12 §3). */
export function cmsHeroKey(extension: string): string {
  return `cms/hero/${ulid()}.${extension}`
}
